image: dal3k/ero1:latest

precommit-job:
  stage: build
  script:
    - pre-commit run -a

build-job:
  stage: build
  script:
    - echo "building..."
    - echo "Build complete"

unit-job:
  needs: [build-job]
  stage: test
  script:
    - pytest --cov=./ -v --junitxml=report.xml
    - coverage xml
  artifacts:
    when: always
    reports:
      cobertura: coverage.xml
      junit: report.xml

functionnal-job:
  needs: [build-job]
  stage: test
  script: echo "running functionnal tests..."

integration-job:
  needs: [build-job]
  stage: test
  script: echo "running integration tests..."

deploy:
  needs: [unit-job, functionnal-job, integration-job]
  stage: deploy
  script: echo "deploying..."
