repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-ast
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: end-of-file-fixer
